language: c
dist: bionic
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsoundtouch-dev

script: ./bootstrap && ./configure && make && make test
